version: '3'
services:
  springboot_app:
    build: .
    ports:
      - 8080:8080
    environment:
      JWT_SECRET: yoursecret
      DATABASE_URL: jdbc:postgresql://postgres:5432/postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    container_name: postgres
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      ROOT_PASSWORD: postgres
      PG_SIGNAL_BACKEND_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistent data storage
      - ./init-scripts:/docker-entrypoint-initdb.d  # Init scripts for custom configurations
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
volumes:
  postgres_data: