version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres
    build: .
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  springboot_app:
    container_name: springboot_app
    image: franciscotov9/lexartlabsfranapi
    build: .
    ports:
      - 8080:8080
    environment:
      JWT_SECRET: yoursecret
      DATABASE_URL: jdbc:postgresql://postgres:5432/postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
    depends_on:
      - postgres